version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./bot-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CONVERSATION_MEMORY_SECONDS=$CONVERSATION_MEMORY_SECONDS
    stdin_open: true
    tty: true

volumes:
  db: